sudo apt-get remove docker docker-engine docker.io containerd runc
sudo systemctl start docker
docker run -d --name ssr-with-net-speeder -p 8989:8989 malaohu/ssr-with-net-speeder -s 0.0.0.0 -p 8989 -k 123456 -m aes-256-cfb -o plain -O origin
wget https://github.com/fatedier/frp/releases/download/v0.36.2/frp_0.36.2_linux_amd64.tar.gz
tar xzvf frp_0.36.2_linux_amd64.tar.gz
cd frp_0.36.2_linux_amd64
echo "[common]
server_addr = frp.freefrp.net
server_port = 7000
token = freefrp.net

[ssraaa]
type = tcp
local_ip = 127.0.0.1
local_port = 8989
remote_port = 44987" > frpc.ini
./frpc -c ./frpc.ini

echo 'FINISHING!' >> test

name: SSR

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          sudo apt-get remove docker docker-engine docker.io containerd runc
          sudo systemctl start docker
          docker run -d --name ssr-with-net-speeder -p 8989:8989 malaohu/ssr-with-net-speeder -s 0.0.0.0 -p 8989 ${{ secrets.CONFIG }}
          wget https://github.com/fatedier/frp/releases/download/v0.36.2/frp_0.36.2_linux_amd64.tar.gz
          tar xzvf frp_0.36.2_linux_amd64.tar.gz
          cd frp_0.36.2_linux_amd64
          echo "[common]
          server_addr = frp.freefrp.net
          server_port = 7000
          token = freefrp.net
          
          
          [${{ secrets.ANY }}]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 8989
          remote_port = ${{ secrets.PORT }}" > frpc.ini
          setsid ./frpc -c ./frpc.ini &
          sleep 6h

name: Use Actions Deploy Hexo To Github

on:
  push:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install hexo
        run: sudo npm install hexo-cli -g

      - name: Generate
        env:
          SOURCE_CODE: ${{ secrets.CODE }}
          THEME_WAREHOUSE: ${{ secrets.THEME }}
        run: |
          git clone -b master $SOURCE_CODE gh
          cd gh
          npm install
          rm -rf .github
          rm -rf .gitignore
          git clone $THEME_WAREHOUSE themes/themes
          ${{ secrets.OTHER }}
          hexo generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./gh/public
          publish_branch: hexo
          personal_token: ${{ secrets.TOKEN }}
