name: Use Actions Deploy Hexo To Github

on:
  push:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
      - name: Install hexo
        run: sudo npm install hexo-cli -g

      - name: Generate
        env:
          SOURCE_CODE: ${{ secrets.A }}
          THEME_WAREHOUSE: ${{ secrets.B }}
        run: |
          git clone -b master $SOURCE_CODE gh
          cd gh/themes
          git clone $THEME_WAREHOUSE theme
          cd ../
          ${{ secrets.C }}
          hexo deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./gh/public
          external_repository: ${{ secrets.D }}
          personal_token: ${{ secrets.E }}
